config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :contests, only: [:show, :new, :create] do
    member do
      get 'ranking', to: 'pages#ranking'
      post :invite
      resources :games, only: [:update] do
        member do
          patch 'update_status'
        end
      end
    end
  end

  resources :participations, only: [:show, :new, :create] do
    resources :events, only: [:create, :edit, :update] do
      member do
        patch 'update_status'
      end
    end
    resources :comments, only: [:create]
    resources :bets, only: [:create]
  end

  get '/dashboard', to: "pages#dashboard"
  post '/dashboard', to: "participations#create" #create participation to an existing contest, using a code

end

app/models/contest.rb
class Contest < ApplicationRecord
  belongs_to :creator, class_name: "User"

  has_many :players, dependent: :destroy
  accepts_nested_attributes_for :players
  has_many :participations, dependent: :destroy
  has_many :events, through: :participations
  has_many :games, dependent: :destroy
  has_many :bets_on_events, through: :events, source: :bets, as: :resource
  has_many :bets_on_games, through: :games, source: :bets, as: :resource
  has_many :bets, through: :participations

  validates :category, inclusion: { in: %w[cup league] }, presence: true
  validates :status, inclusion: { in: %w[opened closed finished] }
  validates :title, presence: true
  validates :coins_init, presence: true, numericality: { greater_than: 0 }
  validates :code, uniqueness: true
  validates :players_nb, presence: true

  after_create :generate_grid

  def phases
    Math.log2(players_nb).to_i
  end

  def current_phase
    self.games.where(status: "coming").select(:phase).distinct.map {|e| e.phase}.max
  end

  def contest_finished

  end

  private

  def generate_grid
    GameGridGenerator.new(self).process
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: %I[show invite update_games]

  def show
    redirect_to dashboard_path if current_user.id != @contest.creator_id
    @user = current_user
    @participation = Participation.new
  end

  def new
    @contest = Contest.new
  end

  def create
    @contest = Contest.new(contest_params)
    if @contest.valid?
      @contest = Contest.create!(contest_params)
      @contest.update(code: code_invit)
      redirect_to contest_path(@contest)
    else
      render :new
    end
  end

  def invite
    InvitationMailer.invitation(@contest, params[:email]).deliver_now!
    redirect_to contest_path(@contest)
  end

  private

  def code_invit
    code = ""
    8.times { code += [rand(48..57).chr, rand(97..122).chr, rand(65..90).chr].sample.to_s }
    return code
  end

  def contest_params
    params.require(:contest).permit(:category, :title, :description, :creator_id, :players_nb,
                                    :coins_init, :picture_path, players_attributes: [:name])
  end

  def set_contest
    @contest = Contest.find(params[:id])
  end
end

app/views/contests/_create_participation.html.erb
<%= simple_form_for participation do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= f.hidden_field :user_id, value: user_id %>
  <%= f.hidden_field :contest_id, value: contest_id %>
  <%= f.button :submit, value: 'Bet on this contest' %>
<% end %>

app/views/contests/_invitation_mail.html.erb
<%= form_tag(invite_contest_path(contest), class: 'd-flex') do %>
  <%= text_field_tag :email, "", class: 'form-control', placeholder: 'Enter an email'%>
  <%= submit_tag 'send mail', class: 'btn btn-primary' %>
<% end %>

app/views/contests/_modal_invitation_mail.html.erb
<!-- modal button -->
   <div class="send-email hidden-xs">
      <button type="button" class="btn-send-email" data-toggle="modal" data-target="#mailModal">
        Invite Friends
      </button>
    </div>

    <div class="send-email-mobile hidden-sm hidden-md hidden-lg">
      <button type="button" class="fas fa-envelope" data-toggle="modal" data-target="#mailModal">
      </button>
    </div>

<!-- modal  -->
<div class="modal fade" id="mailModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-dialog-custom" role="document">
    <div class="modal-content modal-content-radius">
      <div class="modal-header modal-noline" id="invitation-modal">
        <%= render 'invitation_mail', contest: contest %>
      </div>
    </div>
  </div>
</div>

app/views/contests/email_user.js.erb
const mail = document.querySelector('#email')

console.log(mail);

app/views/contests/new.html.erb
<div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.8),rgba(0,0,0,0.6)), url(<%= image_path(@contest.picture_path) %>)">
  <div class="show-title">
    New contest
  </div>
</div>

<div class="container">
<%= simple_form_for @contest do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= f.input :category, as: :radio_buttons, collection: ['cup', 'league'] %>
  <%= f.input :title, placeholder: 'Tournoi de la mort' %>
  <%= f.input :description %>
  <%= f.hidden_field :creator_id, value: current_user.id %>
  <%= f.input :players_nb, collection: [2, 4, 8, 16, 32, 64], id: 'players-nb' %>

  <div id="players-fields"></div>

  <%= f.input :coins_init %>
  <%= f.input :picture_path, class: "form-controlform-text text-muted" %>
  <%= f.button :submit, "Create contest", class: "create-event-btn" %>
<% end %>

</div>

app/views/contests/show.html.erb
<div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.8),rgba(0,0,0,0.6)), url(<%= image_path(@contest.picture_path) %>)">
  <div class="show-title">
    <%= @contest.title %>
  </div>
  <div class="bettings-info">
    <% if Participation.where(user_id: @user.id, contest_id: @contest).empty? %>
      <%= render 'create_participation', participation: @participation, user_id: @user.id, contest_id: @contest.id %>
    <% else %>
      <%= link_to 'Go to gambler view', participation_path(Participation.where(user_id: @user.id, contest_id: @contest).first) %>
    <% end %>
    <div class="code-mail">
      <%= render 'modal_invitation_mail', contest: @contest %>
      <div class="code" id="invitation-code">
        <%= @contest.code %>
      </div>
    </div>
  </div>
</div>

<!-- TESTS EN COURS -->
<h2><%= @contest.status %></h2>


<%= @contest.games.select {|e|e[:status] != "closed"}.first.nil? %>

<% if @contest.games.select {|e|e[:status] != "closed"}.first.nil? %>
  <p>finis</p>
<% else %>
<p>pas finis</p>
<% end %>
<br><br><br>

<% @contest.games.each do |game| %>
  <p><%= game.name %> <%= game.score_p_one %> <%= game.score_p_two %> <%= game.status %></p>
  <% if game.choice_win.nil? %>
    <p>not finished</p>
  <% else %>
    <p>finished</p>
  <% end %>
<% end %>
<!-- FIN TESTS -->






<!-- Games -->
<div class="container">
  <h3>Quarter-Finals</h3>

  <div class="brackets">
    <% @contest.games.where(phase: 3).order(:id).each do |game| %>
      <div id="parent-admin-card-<%= game.id %>">
        <%= render 'shared/admin_card', game: game %>
      </div>
    <% end %>
  </div>

  <h3>Semi-Finals</h3>

  <div class="brackets">
    <% @contest.games.where(phase: 2).order(:id).each do |game| %>
      <div id="parent-admin-card-<%= game.id %>">
        <%= render 'shared/admin_card', game: game %>
      </div>
    <% end %>
  </div>

  <h3>Final</h3>

  <div class="brackets">
    <% @contest.games.where(phase: 1).order(:id).each do |game| %>
      <div id="parent-admin-card-<%= game.id %>">
        <%= render 'shared/admin_card', game: game %>
      </div>
    <% end %>
  </div>
</div>