config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :contests, only: [:show, :new, :create] do
    member do
      get 'ranking', to: 'pages#ranking'
      post :invite
      resources :games, only: [:update] do
        member do
          patch 'update_status'
        end
      end
    end
  end

  resources :participations, only: [:show, :new, :create] do
    resources :events, only: [:create, :edit, :update] do
      member do
        patch 'update_status'
      end
    end
    resources :comments, only: [:create]
    resources :bets, only: [:create]
  end

  get '/dashboard', to: "pages#dashboard"
  post '/dashboard', to: "participations#create" #create participation to an existing contest, using a code

end

app/views/shared/_admin_card.html.erb
<div class="card-tournament" id="admin-card-<%= game.id %>">
  <div class="card-display">
    <div class="game-form-row">
      <div class="game-col col-one">
        <%= render 'shared/player_card_body', class: 'card-body', game: game, number: 'one' %>
      </div>
      <div class="game-col col-two">
        <% if game.status == 'coming' %>
          <%= link_to 'Close bets', update_status_game_path(game), method: :patch, class: 'close-bet-btn', remote: true %>
        <% end %>
      </div>
      <div class="game-col col-three">
        <%= render 'shared/player_card_body', class: 'card-body', game: game, number: 'two' %>
      </div>
    </div>

  </div>

  <div class="scores">
    <% if (game.status != 'closed') && (game.status != 'pending') %>
      <%= render 'shared/update_game_score', game: game %>
    <% end %>
  </div>
</div>

app/views/shared/_bet_button.html.erb
<div class="bet-button">
  <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#bet-button-<%= bet.resource.class.to_s %>-<%= bet.choice %>-<%= index %>" aria-expanded="false" aria-controls="bet-button-<%= bet.resource.class.to_s %>-<%= bet.choice %>-<%= index %>" <%= disabled %>>
    <%= bet.resource.send("choice#{bet.choice}".to_sym) %>
  </button>

  <div class="collapse" id="bet-button-<%= bet.resource.class.to_s %>-<%= bet.choice %>-<%= index %>">
    <div class="well well-bet" id="bet-form-<%= bet.resource.class.to_s %>-<%= bet.choice %>-<%= index %>">
      <%= render 'shared/bet_form', participation: participation, bet: bet %>
    </div>
  </div>
</div>

app/views/shared/_bet_form_modal.html.erb
<%= simple_form_for [participation, bet], remote: true do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="select-choice">
    <input class="choice" type="radio" name="bet[choice]" value=1 id="select-<%= resource.class.to_s %>-one-<%= resource.id %>">
    <label for="select-<%= resource.class.to_s %>-one-<%= resource.id %>">
      <% if resource.class.to_s == 'Game' %>
        <%= image_tag resource.player_one.picture_path, class: "avatar-player-bet", alt: "avatar-player" %>
      <% elsif resource.class.to_s == 'Event' %>
        <span class="event-choice-bet"><%= resource.choice_one %></span>
      <% end %>
    </label>
    <input class="choice" type="radio" name="bet[choice]" value=2 id="select-<%= resource.class.to_s %>-two-<%= resource.id %>">
    <label for="select-<%= resource.class.to_s %>-two-<%= resource.id %>">
      <% if resource.class.to_s == 'Game' %>
        <%= image_tag resource.player_two.picture_path, class: "avatar-player-bet", alt: "avatar-player" %>
      <% elsif resource.class.to_s == 'Event' %>
        <span class="event-choice-bet"><%= resource.choice_two %></span>
      <% end %>
    </label>
  </div>
  <%= f.input :amount, label: "Show me what you got", placeholder: "How much?"%>
  <div class="betcoins-remaining">
    (<span class="label-betcoins-remaining"><%= participation.betcoins %></span>Ƀ remaining)
  </div>
  <%= f.hidden_field :resource_id, value: resource.id %>
  <%= f.hidden_field :resource_type, value: resource.class.to_s %>
  <%= f.button :submit, class: 'btn btn-info', value: "Kick bets!"%>
<% end %>

app/views/shared/_bet_function_modal.html.erb
<button type="button" class="bet-button-display" data-toggle="modal" data-target="#<%= resource.class.to_s %>Modal<%= resource.id %>">
  Bet now!
</button>

<!-- Modal -->
<div class="modal fade" id="<%= resource.class.to_s %>Modal<%= resource.id %>" tabindex="-1" role="dialog" aria-labelledby="<%= resource.class.to_s %>Modal<%= resource.id %>Label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="bet-title"><%= "#{resource.choice_one.capitalize} VS #{resource.choice_two.capitalize}" %></h4>
      </div>
      <div class="modal-body">
        <%= render "shared/bet_form_modal", participation: participation, resource: resource, bet: Bet.new %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_comments_flow.html.erb
<% unless resource.comments.empty? %>
  <% resource.comments.order(created_at: :asc).each do |comment| %>
    <div class="comment">
      <%= image_tag comment.user.picture_path, alt: "No PP", class: 'comments-avatar' %>
      <span class="comments-nickname"><%= comment.user.nickname %></span>
      <div class="comments-content"><%= comment.content %></div>
    </div>
  <% end %>
<% end %>

<% comment = Comment.new(resource: resource) %>
<div class="comment">
  <%= simple_form_for([participation, comment], remote: true) do |f| %>
    <%= f.input :resource_id, as: :hidden %>
    <%= f.input :resource_type, as: :hidden %>
    <%= f.input :content, label: 'Share your expert opinion', label_html: { class: 'comments-form-label' }, as: :string %>
  <% end %>
</div>

app/views/shared/_event_settings.html.erb
<div class="flex-event-settings">


  <%# Update result of event if CurrentUser is the creator AND the Winner is not defined yet %>

  <div class="form-event-edit">
    <%= simple_form_for [participation, event], remote: true do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <%= f.input :choice_win, label: "#{event.title}", as: :radio_buttons, collection: [[1, event.choice_one], [2, event.choice_two]], label_method: :last, value_method: :first, required: true %>
      <%= f.submit "Validate", class: 'btn-create-event' %>
    <% end %>
  </div>

  <div class="close-event-btn-edit">
    <% if event.status == 'coming' %>
      <%= link_to 'Close bets', update_status_participation_event_path(participation, event), method: :patch, class: 'close-bet-btn-modal' %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_game_display_card.html.erb
<div class="card-tournament <%= resource.class.to_s %>-card" data-resource-type="<%= resource.class.to_s %>" data-resource-id="<%= resource.id %>" id="<%= resource.class.to_s %>-<%= resource.id %>">

  <%#= TITLE IF EVENT %>

  <% if resource.class.to_s == 'Event' %>
    <div class="event-card-title"><%= resource.title %></div>
  <% end %>

  <%#= FLEX BOX %>

  <div class="card-display <%= resource.class.to_s %>-card-height">

  <%#= CHOICE ONE %>

    <% if resource.class.to_s == 'Game' %>
      <%= render 'shared/player_card_body', class: 'card-body', game: resource, number: 'one' %>
    <% elsif resource.class.to_s == 'Event' %>
      <%= render 'shared/event_choice_card_body', event: resource, number: 'one' %>
    <% end %>

  <%#= BOX INFO %>

    <div class="whole-info-box text-center">

      <%= render 'shared/odds_sums', resource: resource, class: 'game-info-box' %>
      <% if resource.betable?(current_user) %>

        <%#= Display BET NOW button (Game is betable) %>
        <%= render 'shared/bet_function_modal', resource: resource, participation: participation %>

      <% elsif (resource.class.to_s == 'Event') || (resource.player_one && resource.player_two) %>

        <% bet = Bet.where(participation: participation, resource: resource).first %>
        <% if bet && bet.gains %>

          <%#= Bet is closed %>
          <%= render 'shared/your_gains', bet: bet %>
        <% elsif bet %>

          <%#= Bet is pending %>
          <%= render 'shared/your_bet', bet: bet %>
        <% end %>

      <% else %>
        Incoming...
      <% end %>
    </div>

  <%#= CHOICE TWO %>

    <% if resource.class.to_s == 'Game' %>
      <%= render 'shared/player_card_body', class: 'card-body', game: resource, number: 'two' %>
    <% elsif resource.class.to_s == 'Event' %>
      <%= render 'shared/event_choice_card_body', event: resource, number: 'two' %>
    <% end %>

  </div>

  <%# COMMENTS %>

  <div class="footer-icons">
    <%= render 'shared/comments_collapse', resource: resource, participation: participation %>

    <%# Update event status if it's still 'coming' %>

    <% if resource.class.to_s == 'Event' %>
      <!-- Button trigger modal -->
      <% if (resource.user == participation.user) && !(resource.choice_win) %>

        <button type="button" class="btn-event-settings" data-toggle="modal" data-target="#settings-event-<%= resource.id %>">
          <i class="fas fa-cog"></i>
        </button>

        <!-- Modal -->

        <%= render 'shared/modal_event_settings', resource: resource, participation: participation %>

      <% end %>

    <% end %>

  </div>
</div>

app/views/shared/_navbar.html.erb
<%= link_to '', dashboard_path, class: "fas fa-th", id: "dashboard-shortcut" %>
<div class="btn-group" id="home-menu">
  <button type="button" class="btn btn-default fas fa-power-off dropdown-toggle" id="home-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Homepage", root_path %></li>
    <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %></a>
      <% end %>
    </li>
  </ul>
</div>

app/views/shared/_odds_on_player.html.erb
<div class="odds-on-player">
  <% if (resource.class.to_s == 'Event' && resource.choice_one && resource.choice_two) || (resource.class.to_s == 'Game' && resource.player_one && resource.player_two) %>

    <%= resource.send("odds_choice_#{number}") ? "(" + resource.send("odds_choice_#{number}").round(2).to_s + ")" : ""  %>
  <% end %>
</div>

app/views/shared/_plus_button.html.erb
<div class="plus-container">
  <div class="plus-circle">
    <i class="fas fa-plus"></i>
  </div>
</div>

app/views/shared/_update_game_score.html.erb
<%= simple_form_for game, html: {class: "game-form-grid"}, remote: true do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="game-form-row">
      <div class="game-col col-one">
        <%= f.input :score_p_one, label: false %>
      </div>
      <div class="game-col col-two">
        <%= f.button :submit, value: 'Validate', class: "btn-validate-bet" %>
      </div>
      <div class="game-col col-three">
        <%= f.input :score_p_two, label: false %>
      </div>
  </div>

<% end %>

app/views/shared/_your_bet.html.erb
<div class="you-bet-info">
  <p>You bet<br>
  <strong><%= bet.amount %> Ƀ</strong><br>
  on <%= bet.resource.send("choice#{bet.choice}".to_sym).capitalize %></p>
</div>

app/views/shared/_your_gains.html.erb
<div class="your-gains">
  <% gains = (bet.gains - bet.amount).round(1) %>
  <div class="<%= gains > 0 ? 'win' : 'loose' %>-gains">
  <%= '+' if gains > 0 %><%= gains %> <i class="fas fa-coins"></i>
  </div>
</div>