config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :contests, only: [:show, :new, :create] do
    member do
      get 'ranking', to: 'pages#ranking'
      post :invite
      resources :games, only: [:update] do
        member do
          patch 'update_status'
        end
      end
    end
  end

  resources :participations, only: [:show, :new, :create] do
    resources :events, only: [:create, :edit, :update] do
      member do
        patch 'update_status'
      end
    end
    resources :comments, only: [:create]
    resources :bets, only: [:create]
  end

  get '/dashboard', to: "pages#dashboard"
  post '/dashboard', to: "participations#create" #create participation to an existing contest, using a code

end

app/views/pages/_invitation.html.erb
  <%= form_tag(participations_path, remote: true, class: 'd-flex') do %>
    <%= text_field_tag :code, "", class: 'form-control code-input', placeholder: 'Enter your code'%>
    <%= submit_tag 'Join contest!', class: 'btn btn-primary code-submit' %>
  <% end %>

app/views/pages/_modal_invitation.html.erb
<!-- modal  -->
<div class="modal fade" id="invitationModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-dialog-custom" role="document">
    <div class="modal-content modal-content-radius">
      <div class="modal-header modal-noline" id="invitation-modal">
        <%= render 'invitation' %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_podium.html.erb
<div class="flex-podium">
  <div class="podium-container">
    <div class="flex-image-podium">
      <%= image_tag "podium.png", alt: "Brilliant podium", id: 'podium-img' %>

      <% if @participations[0] %>
        <%= image_tag @participations[0].user.picture_path, alt: "alttext", class: 'podium-avatar podium-p1' %>
      <% end %>
      <% if @participations[1] %>
        <%= image_tag @participations[1].user.picture_path, alt: "alttext", class: 'podium-avatar podium-p2' %>
      <% end %>
      <% if @participations[2] %>
        <%= image_tag @participations[2].user.picture_path, alt: "alttext", class: 'podium-avatar podium-p3' %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.8),rgba(0,0,0,0.6)), url(<%= image_path("dashboard-banner.jpg") %>)">
  <div class="show-title" id ="dashboard-title">
    My contests
  </div>
</div>

<div class="container container-gambler">
  <h3>As Gambler</h3>
  <div class="cards">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card-container">
          <div class="card-contest">
            <!-- modal button -->
            <div class="plus-btn-pos" data-toggle="modal" data-target="#invitationModal">
              <%= render 'shared/plus_button' %>
            </div>
          </div>
        </div>
        <%= render 'modal_invitation' %>
      </div>
      <% @user.participations.map { |e| e.contest }.each do |contest|%>
        <% contest.participations.where(user: @user).each do |participation| %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="card-container">
              <%= link_to "", participation_path(participation) %>
              <div class="card-contest contest-image" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path(contest.picture_path) %>)">
                <div id="title"><%= contest.title %></div>
              </div>
              <div class="details">
                <span class="gambler">
                  <span id="number-gambler"> <%= contest.participations.count %> </span>
                  <i class="fas fa-user-friends" id="icone-people"></i>
                </span>
                <div class="coins">
                  <span id="number-coins"> <%= participation.betcoins %></span>
                  <span class="fas fa-coins"></span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<!-- Display contest create -->
<div class="container">
  <h3>As organizer</h3>
  <div class="cards">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card-container">
          <div class="card-contest">
            <div class="plus-btn-pos">
              <%= link_to new_contest_path, class: "plus-link" do %>
                <%= render 'shared/plus_button' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% @user.contests.each do |contest| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="card-container">
              <div class="card-contest contest-image" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path(contest.picture_path) %>)">
                <%= link_to "", contest_path(contest) %>
                <div id="title"><%= contest.title %></div>
              </div>
              <div class="details">
                <span class="gambler">
                  <span id="number-gambler"> <%= contest.participations.count %> </span>
                  <i class="fas fa-user-friends" id="icone-people"></i>
                </span>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!-- Titles -->
<div class="content">
  <div class="title-menu">
    <h1>
      Kick my <span id="b-letter">Ƀ</span>ets
    </h1>
    <h2>
      Bet me if you can
    </h2>
    <div id="go-btn-homepage">
       <a href="/dashboard" class="button-go">
        <div class="qube">
           <div class="front">Go!</div>
           <div class="back">Ready to kick?</div>
        </div>
      </a>
    </div>
  </div>
</div>

<div class="pycto">
  <div class="pycto-claim">
    <div class="text-claim">
      <div class="text-accroch">
        Organize contests between friends and colleagues. <br>
        Forecast and bet on the outcome of the games.
    </div>
      <div class="page2-link">
       <%= link_to "New contest", new_contest_path, class: "btn btn-lg btn-primary" %>
       <%= link_to "Join contest", dashboard_path, class: "btn btn-lg btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/ranking.html.erb
<div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.8),rgba(0,0,0,0.6)), url(<%= image_path(@contest.picture_path) %>)">
  <div class="show-title">
    <%= "#{@contest.title} - Podium" %>
  </div>
  <%#= LINKS TO GO BACK ON ADMIN/GAMBLER VIEWS %>
  <div class="bettings-info">
    <% unless Participation.where(user: current_user, contest: @contest).empty? %>
      <%= link_to participation_path(Participation.where(user: current_user, contest: @contest).first) do %>
        <i class="fas fa-chevron-left"></i> Gambler view
      <% end %>
    <% end %>
    <% if @contest.creator_id == current_user.id %>
      <%= link_to contest_path(@contest) do %>
        Admin view <i class="fas fa-chevron-right"></i>
      <% end %>
    <% end %>
</div>
</div>

<div class="container">

  <%#= PODIUM %>

  <%= render 'podium', players: @participations.map{ |participation| participation.user } %>

  <%#= RANKING TABLE %>

  <table id="ranking-table">
    <thead>
      <tr class="ranking-tr">
        <th class="ranking-th td-rank"><i class="fas fa-trophy"></i></th>
        <th class="ranking-th" colspan="2">Player</th>
        <th class="ranking-th td-betcoins">Score</th>
        <th class="ranking-th td-bets"><i class="fas fa-angle-up"></i></th>
        <th class="ranking-th td-bets"><i class="fas fa-angle-down"></i></th>
      </tr>
    </thead>
    <tbody>
      <% @participations.each_with_index do |participation, index| %>
        <tr class="ranking-tr <%= 'even-row' if index.even? %>">
          <td class="ranking-td td-rank"><strong><%= index + 1 %></strong></td>
          <td class="ranking-td td-avatar"><%= image_tag participation.user.picture_path, class: 'ranking-avatar' %></td>
          <td class="ranking-td"><%= participation.user.nickname %></td>
          <td class="ranking-td td-betcoins"><%= participation.betcoins.round(1) %> Ƀ</td>
          <td class="ranking-td td-bets"><%= Bet.where(participation_id: participation.id).where('gains > 0').count %></td>
          <td class="ranking-td td-bets"><%= Bet.where(participation_id: participation.id).where('gains = 0').count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>